spring:
  datasource:
    url: jdbc:h2:mem:jwt-example
    driver-class-name: org.h2.Driver
    username: sa
    password:
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml  
jwt:
  header: Authorization
  secret:
  token-validity-in-seconds: 86400